### ISSUE TITLE
Rails 7 and JRuby 9.4.8.0

### ISSUE THREAD

**Issue by damuz91** [rammpeter/jarbler#20]
Good day!
I am new into JRuby and for political reasons my Ruby on Rails project has to be delivered as a Jar file 😅. I see Jarbler as an alternative to abandoned Warbler, I saw your comments about creating Jarbler to perform as an alternative of Warbler, much appreciated.

I have installed the Jarbler gem in JRuby 9.4.8.0. My Rails 7.2 application mostly use default Rails gems and when I try to use the `jarble` command I get the following error. I believe it is because the `bundle install` command does not execute completely.

Do you think above statement is correct?

```
damuz91@estoyprogramando-5 residuos % jarble
Jarbler release 0.3.1, 2024-07-02 ( https://github.com/rammpeter/jarbler )

No configuration file found at /Users/damuz91/Developer/cartoro/residuos/config/jarble.rb. Using default values.
Used configuration values are:
  compile_ruby_files:       false
  excludes:                 ["tmp/cache", "tmp/pids", "tmp/sockets", "vendor/bundle", "vendor/cache", "vendor/ruby"]
  excludes_from_compile:    []
  executable:               bin/rails
  executable_params:        ["server", "-e", "production", "-p", "8080"]
  includes:                 ["app", "bin", "config", "config.ru", "db", "Gemfile", "Gemfile.lock", "lib", "log", "public", "Rakefile", "script", "vendor", "tmp"]
  jar_name:                 residuos.jar
  jruby_version:            9.4.8.0

Fetching jruby-jars-9.4.8.0.gem
Error: Could not find rails-7.2.2, sprockets-rails-3.5.2, pg-1.5.9, sqlite3-2.2.0, puma-6.4.3, importmap-rails-2.0.3, turbo-rails-2.0.11, stimulus-rails-1.3.4, jbuilder-2.13.0, devise-4.9.4, devise-jwt-0.12.1, bootsnap-1.18.4, dotenv-rails-3.1.4, byebug-11.1.3, brakeman-6.2.2, rubocop-rails-omakase-1.0.0, web-console-4.2.1, capybara-3.40.0, actioncable-7.2.2, actionmailbox-7.2.2, actionmailer-7.2.2, actionpack-7.2.2, actiontext-7.2.2, actionview-7.2.2, activejob-7.2.2, activemodel-7.2.2, activerecord-7.2.2, activestorage-7.2.2, activesupport-7.2.2, railties-7.2.2, nio4r-2.7.4, responders-3.1.1, warden-jwt_auth-0.10.0, msgpack-1.7.3, racc-1.8.1, rubocop-1.68.0, rubocop-minitest-0.36.0, rubocop-performance-1.22.1, rubocop-rails-2.27.0, nokogiri-1.16.7, xpath-3.2.0, websocket-driver-0.7.6, zeitwerk-2.7.1, mail-2.8.1, rails-dom-testing-2.2.0, rails-html-sanitizer-1.6.0, globalid-1.2.1, bigdecimal-3.1.8, irb-1.14.1, dry-auto_inject-1.0.1, dry-configurable-1.2.0, jwt-2.9.3, json-2.8.1, language_server-protocol-3.17.0.3, parallel-1.26.3, parser-3.3.6.0, rainbow-3.1.1, rubocop-ast-1.34.0, ruby-progressbar-1.13.0, unicode-display_width-2.6.0, net-imap-0.5.0, loofah-2.23.1, rdoc-6.7.0, reline-0.5.10, dry-core-1.0.2, ast-2.4.2, date-3.4.0, psych-5.2.0, io-console-0.7.2 in locally installed gems
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/definition.rb:605:in `materialize'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/definition.rb:201:in `specs'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/definition.rb:268:in `specs_for'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/runtime.rb:18:in `setup'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler.rb:164:in `setup'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/jarbler-0.3.1/lib/jarbler/builder.rb:142:in `gem_dependencies'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/jarbler-0.3.1/lib/jarbler/builder.rb:115:in `copy_needed_gems_to_staging'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/jarbler-0.3.1/lib/jarbler/builder.rb:34:in `build_jar'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/jarbler-0.3.1/lib/jarbler.rb:17:in `run'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/jarbler-0.3.1/bin/jarble:8:in `<main>'
org/jruby/RubyKernel.java:1220:in `load'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/bin/jarble:25:in `<main>'
Bundler::GemNotFound: Could not find rails-7.2.2, sprockets-rails-3.5.2, pg-1.5.9, sqlite3-2.2.0, puma-6.4.3, importmap-rails-2.0.3, turbo-rails-2.0.11, stimulus-rails-1.3.4, jbuilder-2.13.0, devise-4.9.4, devise-jwt-0.12.1, bootsnap-1.18.4, dotenv-rails-3.1.4, byebug-11.1.3, brakeman-6.2.2, rubocop-rails-omakase-1.0.0, web-console-4.2.1, capybara-3.40.0, actioncable-7.2.2, actionmailbox-7.2.2, actionmailer-7.2.2, actionpack-7.2.2, actiontext-7.2.2, actionview-7.2.2, activejob-7.2.2, activemodel-7.2.2, activerecord-7.2.2, activestorage-7.2.2, activesupport-7.2.2, railties-7.2.2, nio4r-2.7.4, responders-3.1.1, warden-jwt_auth-0.10.0, msgpack-1.7.3, racc-1.8.1, rubocop-1.68.0, rubocop-minitest-0.36.0, rubocop-performance-1.22.1, rubocop-rails-2.27.0, nokogiri-1.16.7, xpath-3.2.0, websocket-driver-0.7.6, zeitwerk-2.7.1, mail-2.8.1, rails-dom-testing-2.2.0, rails-html-sanitizer-1.6.0, globalid-1.2.1, bigdecimal-3.1.8, irb-1.14.1, dry-auto_inject-1.0.1, dry-configurable-1.2.0, jwt-2.9.3, json-2.8.1, language_server-protocol-3.17.0.3, parallel-1.26.3, parser-3.3.6.0, rainbow-3.1.1, rubocop-ast-1.34.0, ruby-progressbar-1.13.0, unicode-display_width-2.6.0, net-imap-0.5.0, loofah-2.23.1, rdoc-6.7.0, reline-0.5.10, dry-core-1.0.2, ast-2.4.2, date-3.4.0, psych-5.2.0, io-console-0.7.2 in locally installed gems
                  materialize at /Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/definition.rb:605
                        specs at /Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/definition.rb:201
                    specs_for at /Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/definition.rb:268
                        setup at /Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/runtime.rb:18
                        setup at /Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler.rb:164
             gem_dependencies at /Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/jarbler-0.3.1/lib/jarbler/builder.rb:142
  copy_needed_gems_to_staging at /Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/jarbler-0.3.1/lib/jarbler/builder.rb:115
                    build_jar at /Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/jarbler-0.3.1/lib/jarbler/builder.rb:34
                          run at /Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/jarbler-0.3.1/lib/jarbler.rb:17
                       <main> at /Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/jarbler-0.3.1/bin/jarble:8
                         load at org/jruby/RubyKernel.java:1220
                       <main> at /Users/damuz91/.rbenv/versions/jruby-9.4.8.0/bin/jarble:25
```

If so, I am trying to sort out how to make the bundle install command to execute completely but I think this would be out of the scope of Jarbler project. Still any lights would be appreciated and I will leave this Issue here in case this enlighten someone in the future. It mentions that I should install development tools first but I already did.

```
damuz91@estoyprogramando-5 residuos % bundle install
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using zeitwerk 2.6.18 (was 2.7.1)
Fetching ast 2.4.2
Fetching json 2.8.1
Fetching language_server-protocol 3.17.0.3
Installing io-console 0.7.2 with native extensions
Installing racc 1.8.1 with native extensions
Installing bigdecimal 3.1.8 with native extensions
Installing date 3.4.0 with native extensions
Installing byebug 11.1.3 with native extensions
Installing msgpack 1.7.3 with native extensions
Installing ast 2.4.2
Installing nio4r 2.7.4 with native extensions
Installing json 2.8.1 with native extensions
Fetching parallel 1.26.3
Installing parallel 1.26.3
Installing language_server-protocol 3.17.0.3
Installing pg 1.5.9 with native extensions
Fetching rainbow 3.1.1
Installing rainbow 3.1.1
Fetching ruby-progressbar 1.13.0
Installing ruby-progressbar 1.13.0
Fetching unicode-display_width 2.6.0
Installing unicode-display_width 2.6.0
Fetching jwt 2.9.3
Installing jwt 2.9.3
Installing websocket-driver 0.7.6 with native extensions
Installing psych 5.2.0 with native extensions
Fetching dry-core 1.0.2
Fetching sqlite3 2.2.0
Installing dry-core 1.0.2
Installing sqlite3 2.2.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bigdecimal-3.1.8/ext/bigdecimal
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/bin/jruby -I
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib extconf.rb
checking for __builtin_clz()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/bin/jruby
RuntimeError: The compiler failed to generate an executable file.
You have to install development tools first.

try_do at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:456
try_compile at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:571
with_werror at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:524
try_compile at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:571
  have_builtin_func at extconf.rb:6
checking_for at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:942
postpone at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:350
open at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:320
postpone at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:350
open at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:320
postpone at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:346
checking_for at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:941
  have_builtin_func at extconf.rb:5
             <main> at extconf.rb:18

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/extensions/universal-java-23/3.1.0/bigdecimal-3.1.8/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bigdecimal-3.1.8
for inspection.
Results logged to
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/extensions/universal-java-23/3.1.0/bigdecimal-3.1.8/gem_make.out

/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/ext/builder.rb:102:in
`run'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/ext/ext_conf_builder.rb:28:in
`build'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/ext/builder.rb:171:in
`build_extension'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/ext/builder.rb:205:in
`block in build_extensions'
  org/jruby/RubyArray.java:1981:in `each'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/ext/builder.rb:202:in
`build_extensions'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/installer.rb:843:in
`build_extensions'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/rubygems_gem_installer.rb:111:in
`build_extensions'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/rubygems_gem_installer.rb:30:in
`install'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/source/rubygems.rb:205:in
`install'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/installer/gem_installer.rb:55:in
`install'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/installer/gem_installer.rb:17:in
`install_from_spec'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/installer/parallel_installer.rb:133:in
`do_install'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/installer/parallel_installer.rb:124:in
`block in worker_pool'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/worker.rb:62:in
`apply_func'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/worker.rb:57:in
`block in process_queue'
  org/jruby/RubyKernel.java:1722:in `loop'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/worker.rb:54:in
`process_queue'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/worker.rb:90:in
`block in create_threads'

An error occurred while installing bigdecimal (3.1.8), and Bundler
cannot continue.

In Gemfile:
  rails was resolved to 7.2.2, which depends on
    actioncable was resolved to 7.2.2, which depends on
      actionpack was resolved to 7.2.2, which depends on
        actionview was resolved to 7.2.2, which depends on
          rails-dom-testing was resolved to 2.2.0, which depends on
            activesupport was resolved to 7.2.2, which depends on
              bigdecimal


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/io-console-0.7.2/ext/io/console
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/bin/jruby -I
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib extconf.rb
checking for rb_io_path()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/bin/jruby
RuntimeError: The compiler failed to generate an executable file.
You have to install development tools first.

try_do at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:456
try_link0 at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:541
try_link at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:556
try_func at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:765
have_func at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:1051
checking_for at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:942
postpone at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:350
open at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:320
postpone at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:350
open at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:320
postpone at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:346
checking_for at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:941
have_func at
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/mkmf.rb:1050
        <main> at extconf.rb:4

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/extensions/universal-java-23/3.1.0/io-console-0.7.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/io-console-0.7.2
for inspection.
Results logged to
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/extensions/universal-java-23/3.1.0/io-console-0.7.2/gem_make.out

/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/ext/builder.rb:102:in
`run'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/ext/ext_conf_builder.rb:28:in
`build'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/ext/builder.rb:171:in
`build_extension'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/ext/builder.rb:205:in
`block in build_extensions'
  org/jruby/RubyArray.java:1981:in `each'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/ext/builder.rb:202:in
`build_extensions'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/installer.rb:843:in
`build_extensions'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/rubygems_gem_installer.rb:111:in
`build_extensions'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/rubygems_gem_installer.rb:30:in
`install'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/source/rubygems.rb:205:in
`install'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/installer/gem_installer.rb:55:in
`install'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/installer/gem_installer.rb:17:in
`install_from_spec'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/installer/parallel_installer.rb:133:in
`do_install'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/installer/parallel_installer.rb:124:in
`block in worker_pool'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/worker.rb:62:in
`apply_func'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/worker.rb:57:in
`block in process_queue'
  org/jruby/RubyKernel.java:1722:in `loop'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/worker.rb:54:in
`process_queue'
/Users/damuz91/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.23/lib/bundler/worker.rb:90:in
`block in create_threads'

An error occurred while installing io-console (0.7.2), and Bundler
cannot continue.

In Gemfile:
  devise-jwt was resolved to 0.12.1, which depends on
    devise was resolved to 4.9.4, which depends on
      responders was resolved to 3.1.1, which depends on
        railties was resolved to 7.2.2, which depends on
          irb was resolved to 1.14.1, which depends on
            reline was resolved to 0.5.10, which depends on
              io-console
```

Thank you!

**Comment by damuz91** [comment]
Small update. I have changed to Ruby 3.3.5 and installed and ran the `jarble` command, it succeeded and now I got my .jar file. But now, and sorry if this is a stupid question, should I was supposed to run the jarble command using jruby instead of MRI ?

```
Jarbler release 0.3.1, 2024-07-02 ( https://github.com/rammpeter/jarbler )

No configuration file found at /Users/damuz91/Developer/cartoro/residuos/config/jarble.rb. Using default values.
Used configuration values are:
  compile_ruby_files:       false
  excludes:                 ["tmp/cache", "tmp/pids", "tmp/sockets", "vendor/bundle", "vendor/cache", "vendor/ruby"]
  excludes_from_compile:    []
  executable:               bin/rails
  executable_params:        ["server", "-e", "production", "-p", "8080"]
  includes:                 ["app", "bin", "config", "config.ru", "db", "Gemfile", "Gemfile.lock", "lib", "log", "public", "Rakefile", "script", "vendor", "tmp"]
  jar_name:                 residuos.jar
  jruby_version:            9.4.9.0

Created jar file /Users/damuz91/Developer/cartoro/residuos/residuos.jar
```

Thank you!

**Comment by rammpeter** [comment]
Hi David,

Please excuse my late answer.

After having the jar file created by jarble you can execute it using „java -jar xy.jar“.

It is o.k. to create the jar file by running jarble with MRI, jRuby is not necessary at this step.

Best regards
Peter

**Comment by rammpeter** [comment]
@damuz91 , quite a long time after we discussed the issue.
Is there something open right now?
